import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { setTimeout as delay } from "node:timers/promises";
import { createCommitJournal } from "../src/commit-journal.mjs";

const entry = { idempotencyKey: "save_12345", saveType: "document_save", canonicalFileKey: "a".repeat(64), baseEtag: '"old"', newEtag: '"new"', beforeDigest: "b".repeat(64), afterDigest: "c".repeat(64), requestDigest: "d".repeat(64), stage: "commit_intent" };
test("journal persists every ordered durable stage and rejects skips", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "journal-")); try { const journal = createCommitJournal({ directory: root }); await journal.begin(entry); await assert.rejects(() => journal.advance(entry, "verified"), { code: "COMMIT_JOURNAL_STAGE_INVALID" }); await journal.advance(entry, "source_replaced"); await journal.advance(entry, "verified"); const done = await journal.advance(entry, "result_published"); assert.equal(done.stage, "result_published"); assert.equal((await journal.read(entry.idempotencyKey)).stage, "result_published"); } finally { await rm(root, { recursive: true, force: true }); } });
test("journal never overwrites a logical save when an idempotency key collides", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "journal-")); try { const journal = createCommitJournal({ directory: root }); await journal.begin(entry); await assert.rejects(() => journal.begin({ ...entry, requestDigest: "e".repeat(64) }), { code: "COMMIT_JOURNAL_IDEMPOTENCY_CONFLICT" }); assert.equal((await journal.read(entry.idempotencyKey)).requestDigest, entry.requestDigest); } finally { await rm(root, { recursive: true, force: true }); } });
test("different document lanes cannot race the same idempotency key into two intents", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "journal-")); try { const a = createCommitJournal({ directory: root }); const b = createCommitJournal({ directory: root }); const results = await Promise.allSettled([a.begin(entry), b.begin({ ...entry, canonicalFileKey: "f".repeat(64) })]); assert.equal(results.filter((result) => result.status === "fulfilled").length, 1); assert.equal(results.find((result) => result.status === "rejected")?.reason.code, "COMMIT_JOURNAL_IDEMPOTENCY_CONFLICT"); } finally { await rm(root, { recursive: true, force: true }); } });
test("an EEXIST observer retries an initially partial intent before checking logical identity", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "journal-")); try { await writeFile(path.join(root, `${entry.idempotencyKey}.json`), "{", "utf8"); const replacement = delay(12).then(() => writeFile(path.join(root, `${entry.idempotencyKey}.json`), `${JSON.stringify(entry, null, 2)}\n`, "utf8")); const journal = createCommitJournal({ directory: root }); await assert.rejects(() => journal.begin({ ...entry, canonicalFileKey: "f".repeat(64) }), { code: "COMMIT_JOURNAL_IDEMPOTENCY_CONFLICT" }); await replacement; } finally { await rm(root, { recursive: true, force: true }); } });
test("a persistently unreadable colliding intent remains invalid", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "journal-")); try { await writeFile(path.join(root, `${entry.idempotencyKey}.json`), "{", "utf8"); const journal = createCommitJournal({ directory: root }); await assert.rejects(() => journal.begin(entry), { code: "COMMIT_JOURNAL_INVALID" }); } finally { await rm(root, { recursive: true, force: true }); } });
