import {
  IconAlertTriangleFilled,
  IconBraces,
  IconCalendarFilled,
  IconCheckbox,
  IconCircleDotFilled,
  IconColumnInsertRight,
  IconDeviceFloppyFilled,
  IconDots,
  IconEyeOff,
  IconFileCodeFilled,
  IconFilterFilled,
  IconGripVertical,
  IconHierarchy,
  IconInfoCircleFilled,
  IconLayoutSidebarRightFilled,
  IconLink,
  IconLinkOff,
  IconPlus,
  IconRotateClockwise2,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconX,
  IconNumber,
  IconRefresh,
  IconRowInsertBottom,
  IconSearch,
  IconSortAscending,
  IconSortDescending,
  IconTableFilled,
  IconTagsFilled,
  IconTextSize,
  IconTextWrap,
  IconTrashFilled,
} from "@tabler/icons-react";

export const icons = {
  search: IconSearch,
  save: IconDeviceFloppyFilled,
  dirty: IconCircleDotFilled,
  incompatible: IconAlertTriangleFilled,
  jsonFile: IconFileCodeFilled,
  csvFile: IconTableFilled,
  textField: IconTextSize,
  wrapText: IconTextWrap,
  numberField: IconNumber,
  checkboxField: IconCheckbox,
  dateField: IconCalendarFilled,
  tagsField: IconTagsFilled,
  sortAscending: IconSortAscending,
  sortDescending: IconSortDescending,
  filter: IconFilterFilled,
  addRow: IconRowInsertBottom,
  addField: IconPlus,
  delete: IconTrashFilled,
  detailPanel: IconLayoutSidebarRightFilled,
  previous: IconChevronLeft,
  next: IconChevronRight,
  openDetail: IconLayoutSidebarRightFilled,
  close: IconX,
  refresh: IconRefresh,
  hidden: IconEyeOff,
  reset: IconRotateClockwise2,
  dragHandle: IconGripVertical,
  more: IconDots,
  info: IconInfoCircleFilled,
  check: IconCheck,
  nested: IconHierarchy,
  json: IconBraces,
  relation: IconLink,
  relationOff: IconLinkOff,
} as const;
