import {
  IconAlertTriangleFilled,
  IconAdjustmentsHorizontal,
  IconBraces,
  IconBorderAll,
  IconCalendarFilled,
  IconCircleCaretDownFilled,
  IconCheckbox,
  IconCircleDotFilled,
  IconColumnInsertRight,
  IconCopy,
  IconDeviceFloppyFilled,
  IconDots,
  IconEdit,
  IconEyeOff,
  IconFileCodeFilled,
  IconFolderFilled,
  IconFilter2,
  IconGripVertical,
  IconHierarchy,
  IconHourglassEmpty,
  IconInfoCircleFilled,
  IconLayoutSidebarRightFilled,
  IconLink,
  IconLinkOff,
  IconPlus,
  IconPower,
  IconRotateClockwise2,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconX,
  IconNumber,
  IconRefresh,
  IconSettings,
  IconRowInsertBottom,
  IconSearch,
  IconSortAscending,
  IconSortDescending,
  IconTableFilled,
  IconTagsFilled,
  IconTextSize,
  IconTextWrap,
  IconTrashFilled,
} from "@tabler/icons-react";

export const icons = {
  search: IconSearch,
  save: IconDeviceFloppyFilled,
  dirty: IconCircleDotFilled,
  circleDot: IconCircleDotFilled,
  borderAll: IconBorderAll,
  incompatible: IconAlertTriangleFilled,
  jsonFile: IconFileCodeFilled,
  csvFile: IconTableFilled,
  table: IconTableFilled,
  textField: IconTextSize,
  wrapText: IconTextWrap,
  numberField: IconNumber,
  checkboxField: IconCheckbox,
  selectField: IconCircleCaretDownFilled,
  multiSelectField: IconTagsFilled,
  dateField: IconCalendarFilled,
  tagsField: IconTagsFilled,
  sortAscending: IconSortAscending,
  sortDescending: IconSortDescending,
  filter: IconFilter2,
  addRow: IconRowInsertBottom,
  addField: IconPlus,
  delete: IconTrashFilled,
  detailPanel: IconLayoutSidebarRightFilled,
  previous: IconChevronLeft,
  next: IconChevronRight,
  chevronDown: IconChevronDown,
  openDetail: IconLayoutSidebarRightFilled,
  close: IconX,
  power: IconPower,
  copy: IconCopy,
  refresh: IconRefresh,
  edit: IconEdit,
  adjust: IconAdjustmentsHorizontal,
  settings: IconSettings,
  hidden: IconEyeOff,
  reset: IconRotateClockwise2,
  dragHandle: IconGripVertical,
  more: IconDots,
  info: IconInfoCircleFilled,
  hourglassEmpty: IconHourglassEmpty,
  check: IconCheck,
  nested: IconHierarchy,
  folder: IconFolderFilled,
  json: IconBraces,
  relation: IconLink,
  relationOff: IconLinkOff,
} as const;
